apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: configurator
  name: configurator
spec:
  containers:
  - env:
    - name: HYDRA_ACTION_PREFIX
      value: 'actions:hydra:'
    - name: HYDRA_ADMIN_URL
      value: http://hydra:4445
    - name: HYDRA_RESOURCE_PREFIX
      value: 'resources:hydra:'
    - name: HYDRA_SUBJECT_PREFIX
      value: 'subjects:hydra:'
    - name: HYDRA_URL
      value: http://hydra:4444
    - name: KETO_ACTION_PREFIX
      value: 'actions:keto:'
    - name: KETO_RESOURCE_PREFIX
      value: 'resources:keto:'
    - name: KETO_URL
      value: http://keto:4466
    - name: OATHKEEPER_ACTION_PREFIX
      value: 'actions:oathkeeper:'
    - name: OATHKEEPER_API_URL
      value: http://oathkeeper-api:4456
    - name: OATHKEEPER_HYDRA_CLIENT_ID
      value: clients:oathkeeper-client
    - name: OATHKEEPER_HYDRA_CLIENT_SECRET
      value: dummy-oathkeeper-secret
    - name: OATHKEEPER_HYDRA_JWK_SET_ID
      value: jwk:oathkeeper
    - name: OATHKEEPER_PROXY_URL
      value: http://oathkeeper-proxy:4455
    - name: OATHKEEPER_RESOURCE_PREFIX
      value: 'resources:oathkeeper:'
    - name: RESOURCE_SERVER_URL
      value: http://resource-server:4478
    image: configurator
    name: configurator
    resources: {}
  restartPolicy: OnFailure
status: {}
