apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-localhost
  name: consumer-localhost
spec:
  ports:
  - name: "4477"
    port: 4477
    targetPort: 4477
  selector:
    io.kompose.service: consumer-localhost
status:
  loadBalancer: {}
