apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hydra-migrate
  name: hydra-migrate
spec:
  containers:
  - args:
    - migrate
    - sql
    - postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    env:
    - name: HYDRA_SYSTEM_SECRET
      value: youReallyNeedToChangeThis
    - name: LOG_LEVEL
      value: debug
    image: 'oryd/hydra:'
    name: hydra-migrate
    resources: {}
  restartPolicy: OnFailure
status: {}
