apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hydra
  name: hydra
spec:
  containers:
  - args:
    - serve
    - all
    - --dangerous-force-http
    env:
    - name: CORS_ALLOWED_METHODS
      value: POST,GET,PUT,DELETE
    - name: CORS_ENABLED
      value: "true"
    - name: DATABASE_URL
      value: postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    - name: LOG_LEVEL
      value: debug
    - name: OAUTH2_CONSENT_URL
      value: http://:4488/consent
    - name: OAUTH2_ISSUER_URL
      value: http://:4444
    - name: OAUTH2_LOGIN_URL
      value: http://:4488/login
    - name: OAUTH2_SHARE_ERROR_DEBUG
      value: "1"
    - name: SYSTEM_SECRET
      value: youReallyNeedToChangeThis
    image: hydra
    name: hydra
    ports:
    - containerPort: 4444
    - containerPort: 4445
    resources: {}
  restartPolicy: OnFailure
status: {}
