apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: identity-provider
  name: identity-provider
spec:
  containers:
  - env:
    - name: HYDRA_ADMIN_URL
      value: http://hydra:4445
    - name: NODE_TLS_REJECT_UNAUTHORIZED
      value: "0"
    - name: PORT
      value: "4488"
    image: 'oryd/hydra-login-consent-node:'
    name: identity-provider
    ports:
    - containerPort: 4488
    resources: {}
  restartPolicy: OnFailure
status: {}
