apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keto
  name: keto
spec:
  containers:
  - env:
    - name: CORS_ALLOWED_METHODS
      value: POST,GET,PUT,DELETE
    - name: CORS_ENABLED
      value: "true"
    - name: DATABASE_URL
      value: postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    - name: LOG_LEVEL
      value: debug
    image: 'oryd/keto:'
    name: keto
    ports:
    - containerPort: 4466
    resources: {}
  restartPolicy: OnFailure
status: {}
