apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: oathkeeper-migrate
  name: oathkeeper-migrate
spec:
  containers:
  - args:
    - migrate
    - sql
    - postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    env:
    - name: LOG_LEVEL
      value: debug
    image: 'oryd/oathkeeper:'
    name: oathkeeper-migrate
    resources: {}
  restartPolicy: OnFailure
status: {}
